---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: "100%"
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: quay.io/opendatahub/odh-notebook-controller:latest
          imagePullPolicy: Always
          command:
            - /manager
          args: ["--oauth-proxy-image", "quay.io/lxheryer/oauth2-proxy:202407182059"]
          env:
            - name: OAUTH_PROXY_IMAGE
              valueFrom:
                secretKeyRef:
                  name: phoenix-context
                  key: oauth_proxy_image
            - name: OAUTH_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: phoenix-context
                  key: oauth_issuer_url
            - name: OAUTH_EXTRA_JWT_ISSUERS
              valueFrom:
                secretKeyRef:
                  name: phoenix-context
                  key: oauth_extra_jwt_issuers
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: phoenix-context
                  key: oauth_client_id
            - name: OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: phoenix-context
                  key: oauth_client_secret
            - name: PHOENIX_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: phoenix-context
                  key: phoenix_base_url
            - name: PHOENIX_SERVICE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: phoenix-context
                  key: phoenix_service_client_id
            - name: PHOENIX_SERVICE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: phoenix-context
                  key: phoenix_service_client_secret
            - name: PHOENIX_TOKEN_URL
              valueFrom:
                secretKeyRef:
                  name: phoenix-context
                  key: phoenix_token_url
            - name: PHOENIX_SUBSCRIPTION_TYPE
              value: "sc"
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 256Mi
